language: node_js

node_js:
  - '0.12'

env:
  - BROWSER=PhantomJS
  - BROWSER=ChromeTravisCI
  - BROWSER=Firefox

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@latest
  - npm install -g bower grunt-cli karma-cli
  - bower install --force-latest
  - npm install
  - npm install vinyl-fs@2.2.1
  - npm cache clean

script:
  - cp config.sample.js config.js
  - grunt
  - npm test -- --browsers $BROWSER

after_success:
  - grunt coveralls
